FROM quay.io/centos/centos:stream8

RUN true \
 && dnf -y install skopeo \
 && dnf -y clean all \
 && true

ADD images.txt /opt/mirror/
ADD mirror-images.sh /opt/mirror/

ENV HOME=/opt/mirror
WORKDIR /opt/mirror

CMD ["./mirror-images.sh"]
