---
apiVersion: v1
kind: Pod
metadata:
  name: pod-multi-pvc-fs
spec:
  containers:
    - name: app-container
      image: quay.io/centos/centos:latest
      command: ["/bin/sleep", "infinity"]
      volumeMounts:
        - name: vol-0
          mountPath: /mnt/vol-0
        - name: vol-1
          mountPath: /mnt/vol-1
        - name: vol-2
          mountPath: /mnt/vol-2
  volumes:
    - name: vol-0
      persistentVolumeClaim:
        claimName: rbd-pvc-0
    - name: vol-1
      persistentVolumeClaim:
        claimName: rbd-pvc-1
    - name: vol-2
      persistentVolumeClaim:
        claimName: rbd-pvc-2
