---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephcsi-nvmeof-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
  storageClassName: ocs-storagecluster-ceph-nvmeof
