---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: nvme-pvc-snapshot
spec:
  volumeSnapshotClassName: csi-nvmeplugin-snapclass
  source:
    persistentVolumeClaimName: nvmeof-pvc
