---
# apiVersion: storage.k8s.io/v1beta1 for k8s version 1.33
apiVersion: storage.k8s.io/v1
kind: VolumeAttributesClass
metadata:
  name: high-performance
driverName: nvmeof.csi.ceph.com
parameters:
  rwIosPerSecond: "10000"
  rwMbytesPerSecond: "1000"
