[codespell]
# TODO: enable codespell on retest folder except vendor
skip = .git,./vendor,./docs/design/proposals/images,./actions/retest/*,./api/vendor,go.sum,./e2e/vendor,./internal/nvme/gateway/proto/*.proto,./internal/nvme/gateway/proto/*.pb.go
ignore-words-list = ExtraVersion,extraversion,ba,ro,RO
check-filenames = true
