---
name: commitlint
# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - '*'
permissions:
  contents: read

# cancel the in-progress workflow when PR is refreshed.
concurrency:
  # yamllint disable-line rule:truthy rule:line-length
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  commitlint:
    name: commitlint
    if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: commitlint
        # yamllint disable-line rule:line-length
        run: make containerized-test TARGET=commitlint GIT_SINCE="origin/${GITHUB_BASE_REF}"
