---
name: 'Dependency Review'
# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - '*'


permissions:
  contents: read

# cancel the in-progress workflow when PR is refreshed.
concurrency:
  # yamllint disable-line rule:truthy rule:line-length
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        # yamllint disable-line rule:line-length
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
      - name: 'Dependency Review'
        # yamllint disable-line rule:line-length
        uses: actions/dependency-review-action@3c4e3dcb1aa7874d2c16be7d79418e9b7efd6261  # v4.8.2
        with:
          allow-ghsas: GHSA-f4w6-3rh6-6q4q
