---
# link-check is a GitHub Action that checks for broken links in markdown files
# Reference https://github.com/lycheeverse/lychee-action
name: link-check
# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - '*'
permissions:
  contents: read

# cancel the in-progress workflow when PR is refreshed.
concurrency:
  # yamllint disable-line rule:truthy rule:line-length
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  link-check:
    name: link-check
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: link-check
        run: make containerized-test TARGET=link-check
