---
name: Security scanning
# yamllint disable-line rule:truthy
on:
  schedule:
    # Run weekly on every Monday
    - cron: '0 0 * * 1'
  push:
    tags:
      - v*
    branches:
      - release-*

permissions:
  contents: read

jobs:
  security:
    if: github.repository == 'ceph/ceph-csi'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0

      - name: run Snyk to check for code vulnerabilities
        # yamllint disable-line rule:line-length
        uses: snyk/actions/golang@12140f4059e244892ae643824a95459a102120dd  # master
        env:
          SNYK_TOKEN: ${{ secrets.SYNK_TOKEN }}
