---
name: test-retest-action
# yamllint disable-line rule:truthy
on:
  pull_request:
    branches: [devel]
    paths:
      - 'actions/retest/**'
      - '.github/workflows/test-retest-action.yaml'

permissions:
  contents: read

# cancel the in-progress workflow when PR is refreshed.
concurrency:
  # yamllint disable-line rule:truthy rule:line-length
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Docker build
        # Run cd to avoid loading complete cephcsi directory in docker context
        # while building retest image.
        run: cd actions/retest && docker build -t retest .
