---
name: List TODO's
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - devel

permissions:
  contents: read

jobs:
  tickgit:
    name: tickgit
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - run: make containerized-test TARGET=tickgit
