---
name: List TODO's
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - devel

permissions:
  contents: read

jobs:
  tickgit:
    name: tickgit
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
      - run: make containerized-test TARGET=tickgit
