---
name: List TODO's
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - devel

permissions:
  contents: read

jobs:
  tickgit:
    name: tickgit
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - run: make containerized-test TARGET=tickgit
